# Generated by Django 5.2.8 on 2026-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('institution', "Muassasa o'quvchisi"), ('external', "Tashqi o'quvchi")], default='external', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_name',
            field=models.CharField(blank=True, max_length=200, verbose_name="O'qituvchi ismi"),
        ),
    ]
