# Generated by Django 5.2.8 on 2026-03-28 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_teacher'),
        ('students', '0002_student_student_type_student_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='student',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.teacher', verbose_name="O'qituvchi"),
        ),
    ]
