# Generated by Django 5.2.8 on 2026-04-15 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationsettings_logo_group'),
        ('students', '0003_remove_student_teacher_name_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('institution', 'Institution Student'), ('external', 'External Student')], default='external', max_length=20),
        ),
    ]
