# Generated by Django 5.2.8 on 2026-03-28 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Logo')),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7, verbose_name='Asosiy rang')),
                ('secondary_color', models.CharField(default='#10b981', max_length=7, verbose_name='Ikkinchi rang')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, verbose_name='Facebook')),
                ('allow_student_registration', models.BooleanField(default=True, verbose_name="Talaba ro'yxatdan o'tishiga ruxsat")),
                ('show_leaderboard', models.BooleanField(default=True, verbose_name="Reyting jadvalini ko'rsatish")),
                ('enable_certificates', models.BooleanField(default=True, verbose_name='Sertifikatlarni yoqish')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email xabarnomalar')),
                ('telegram_notifications', models.BooleanField(default=False, verbose_name='Telegram xabarnomalar')),
                ('telegram_bot_token', models.CharField(blank=True, max_length=200, verbose_name='Telegram bot token')),
                ('about_text', models.TextField(blank=True, verbose_name='Biz haqimizda')),
                ('mission', models.TextField(blank=True, verbose_name='Missiya')),
                ('vision', models.TextField(blank=True, verbose_name='Viziya')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tashkilot sozlamalari',
                'verbose_name_plural': 'Tashkilot sozlamalari',
                'db_table': 'organization_settings',
            },
        ),
    ]
