# Generated by Django 5.2.8 on 2026-04-15 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organizationsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationsettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Barcha rasm formatlari qabul qilinadi', null=True, upload_to='logos/', verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('weekdays', models.CharField(help_text='Masalan: monday,wednesday,friday', max_length=200, verbose_name='Dars kunlari')),
                ('lesson_time', models.TimeField(help_text='Masalan: 14:00', verbose_name='Dars vaqti')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_groups', to='organizations.teacher', verbose_name="O'qituvchi")),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
    ]
