# Generated by Django 5.2.8 on 2026-03-28 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Sarlavha')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('address', models.TextField(blank=True, verbose_name='Manzil')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Ish vaqti')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Aloqa ma'lumotlari",
                'verbose_name_plural': "Aloqa ma'lumotlari",
                'db_table': 'contact_info',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Savol')),
                ('answer', models.TextField(verbose_name='Javob')),
                ('category', models.CharField(choices=[('general', 'Umumiy'), ('exams', 'Imtihonlar'), ('students', 'Talabalar'), ('results', 'Natijalar'), ('technical', 'Texnik'), ('billing', "To'lov")], default='general', max_length=100, verbose_name='Kategoriya')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('views', models.IntegerField(default=0, verbose_name="Ko'rishlar soni")),
                ('helpful_count', models.IntegerField(default=0, verbose_name='Foydali deb belgilangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Ko'p beriladigan savol",
                'verbose_name_plural': "Ko'p beriladigan savollar",
                'db_table': 'faqs',
                'ordering': ['order', '-helpful_count'],
            },
        ),
        migrations.CreateModel(
            name='SupportVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('video_url', models.URLField(verbose_name='Video URL (YouTube, Vimeo)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='support/thumbnails/', verbose_name='Rasm')),
                ('category', models.CharField(choices=[('getting_started', 'Boshlash'), ('exams', 'Imtihonlar'), ('students', 'Talabalar'), ('results', 'Natijalar'), ('settings', 'Sozlamalar'), ('other', 'Boshqa')], default='other', max_length=100, verbose_name='Kategoriya')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='Davomiyligi')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yordam videosi',
                'verbose_name_plural': 'Yordam videolari',
                'db_table': 'support_videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism')),
                ('position', models.CharField(max_length=100, verbose_name='Lavozim')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='Rasm')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('order', models.IntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Jamoa a'zosi",
                'verbose_name_plural': "Jamoa a'zolari",
                'db_table': 'team_members',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('category', models.CharField(choices=[('technical', 'Texnik muammo'), ('billing', "To'lov"), ('feature', 'Yangi funksiya'), ('bug', 'Xatolik'), ('other', 'Boshqa')], default='other', max_length=100, verbose_name='Kategoriya')),
                ('status', models.CharField(choices=[('open', 'Ochiq'), ('in_progress', 'Jarayonda'), ('resolved', 'Hal qilindi'), ('closed', 'Yopildi')], default='open', max_length=50, verbose_name='Holat')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('medium', "O'rta"), ('high', 'Yuqori'), ('urgent', 'Shoshilinch')], default='medium', max_length=50, verbose_name='Muhimlik')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support/attachments/', verbose_name='Fayl')),
                ('admin_response', models.TextField(blank=True, verbose_name='Admin javobi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Hal qilingan vaqt')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Yordam so'rovi",
                'verbose_name_plural': "Yordam so'rovlari",
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
