# Generated by Django 5.0.3 on 2026-03-24 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'exams',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Maximum number of uses (null = unlimited)', null=True)),
                ('use_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'exam_links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], default='reading', max_length=20)),
                ('type', models.CharField(choices=[('mcq_single', 'Multiple Choice (Single Answer)'), ('mcq_multiple', 'Multiple Choice (Multiple Answers)'), ('true_false_ng', 'True / False / Not Given'), ('yes_no_ng', 'Yes / No / Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('matching_features', 'Matching Features'), ('matching_sentence_endings', 'Matching Sentence Endings'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flowchart_completion', 'Flow-chart Completion'), ('diagram_labeling', 'Diagram Label Completion'), ('short_answer', 'Short Answer Questions'), ('writing', 'Writing Task')], max_length=30)),
                ('instruction_text', models.TextField(help_text='Instructions for this question')),
                ('content', models.JSONField(default=dict, help_text='Question content (structure varies by type)')),
                ('correct_answer', models.JSONField(default=dict, help_text='Correct answer(s) in JSON format')),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('audio_url', models.URLField(blank=True, help_text='Audio file URL for listening questions', null=True)),
                ('start_time', models.IntegerField(blank=True, help_text='Audio start time in seconds', null=True)),
                ('end_time', models.IntegerField(blank=True, help_text='Audio end time in seconds', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('points', models.IntegerField(default=1, help_text='Points for this question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ['order', 'id'],
            },
        ),
    ]
