# Generated by Django 5.0.3 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio file for listening questions', null=True, upload_to='audio/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_file',
            field=models.ImageField(blank=True, help_text='Image file for diagram questions', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image_url',
            field=models.URLField(blank=True, help_text='Image URL (alternative to file upload)', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='audio_url',
            field=models.URLField(blank=True, help_text='Audio file URL (alternative to file upload)', null=True),
        ),
    ]
