# Generated by Django 5.0.3 on 2026-03-24 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_audio_file_question_image_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice_single', 'Multiple Choice (Single Answer)'), ('multiple_choice_multiple', 'Multiple Choice (Multiple Answers)'), ('true_false_ng', 'True/False/Not Given'), ('yes_no_ng', 'Yes/No/Not Given'), ('matching_headings', 'Matching Headings'), ('matching_information', 'Matching Information'), ('matching_features', 'Matching Features'), ('matching_sentence_endings', 'Matching Sentence Endings'), ('sentence_completion', 'Sentence Completion'), ('summary_completion', 'Summary Completion'), ('note_completion', 'Note Completion'), ('table_completion', 'Table Completion'), ('flowchart_completion', 'Flow-chart Completion'), ('diagram_labeling', 'Diagram Labeling'), ('short_answer', 'Short Answer')], max_length=50)),
                ('title', models.CharField(help_text='e.g., "Questions 1-5"', max_length=255)),
                ('instructions', models.TextField(help_text='Instructions for this group')),
                ('order', models.IntegerField(default=0)),
                ('passage_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_groups/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='examlink',
            name='max_uses',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NoteCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('note_text', models.TextField(help_text='Use _____ for blank')),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True)),
                ('max_words', models.IntegerField(default=2)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceSingleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/mc/')),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'verbose_name': 'Multiple Choice (Single)',
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceMultipleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('question_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/mc/')),
                ('option_a', models.TextField()),
                ('option_b', models.TextField()),
                ('option_c', models.TextField()),
                ('option_d', models.TextField()),
                ('option_e', models.TextField(blank=True)),
                ('option_f', models.TextField(blank=True)),
                ('correct_answers', models.CharField(help_text='Comma-separated: A,B,C', max_length=50)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'verbose_name': 'Multiple Choice (Multiple)',
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchingSentenceEndingsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('sentence_start', models.TextField()),
                ('correct_ending', models.CharField(help_text='A, B, C, etc.', max_length=10)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchingInformationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('information_text', models.TextField()),
                ('correct_paragraph', models.CharField(help_text='A, B, C, etc.', max_length=10)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchingHeadingsQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('paragraph_label', models.CharField(help_text='A, B, C, etc.', max_length=10)),
                ('correct_heading', models.CharField(help_text='i, ii, iii, etc.', max_length=10)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='MatchingFeaturesQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('statement', models.TextField()),
                ('correct_feature', models.CharField(help_text='A, B, C, etc.', max_length=10)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='HeadingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_label', models.CharField(max_length=10)),
                ('heading_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heading_options', to='exams.questiongroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FlowchartCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('flowchart_image', models.ImageField(blank=True, null=True, upload_to='flowcharts/')),
                ('box_position', models.CharField(max_length=50)),
                ('box_context', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True)),
                ('max_words', models.IntegerField(default=2)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='FeatureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_label', models.CharField(max_length=10)),
                ('feature_text', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_options', to='exams.questiongroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DiagramLabelingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('diagram_image', models.ImageField(upload_to='diagrams/')),
                ('label_position', models.CharField(help_text='Position on diagram', max_length=50)),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True, help_text='One per line')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., "Reading Section 1"', max_length=255)),
                ('module', models.CharField(choices=[('reading', 'Reading'), ('listening', 'Listening'), ('writing', 'Writing'), ('speaking', 'Speaking')], max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('passage_text', models.TextField(blank=True, help_text='Reading passage text')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='exams.exam')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='exams.section'),
        ),
        migrations.CreateModel(
            name='SentenceCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('sentence_text', models.TextField(help_text='Use _____ for blank')),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True, help_text='One per line')),
                ('max_words', models.IntegerField(default=3)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='SentenceEndingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_label', models.CharField(max_length=10)),
                ('ending_text', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_options', to='exams.questiongroup')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('question_text', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True, help_text='One per line')),
                ('max_words', models.IntegerField(default=3)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='SummaryCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('summary_text', models.TextField(help_text='Use _____ for blanks')),
                ('has_word_bank', models.BooleanField(default=False)),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True)),
                ('max_words', models.IntegerField(default=2)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='TableCompletionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('row_header', models.CharField(blank=True, max_length=255)),
                ('column_header', models.CharField(blank=True, max_length=255)),
                ('cell_context', models.TextField()),
                ('correct_answer', models.CharField(max_length=255)),
                ('alternative_answers', models.TextField(blank=True)),
                ('max_words', models.IntegerField(default=2)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='TrueFalseNotGivenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(choices=[('TRUE', 'True'), ('FALSE', 'False'), ('NOT GIVEN', 'Not Given')], max_length=20)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.CreateModel(
            name='YesNoNotGivenQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('points', models.IntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Explanation for the answer')),
                ('statement', models.TextField()),
                ('correct_answer', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('NOT GIVEN', 'Not Given')], max_length=20)),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='exams.questiongroup')),
            ],
            options={
                'unique_together': {('question_group', 'question_number')},
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
