# Generated by Django 5.2.8 on 2026-03-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_questiongroup_alter_examlink_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examlink',
            name='resume_password',
            field=models.CharField(blank=True, help_text='Parol imtihonni davom ettirish uchun', max_length=50, null=True),
        ),
    ]
