# Generated by Django 5.2.8 on 2026-04-15 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_examlink_resume_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagramlabelingquestion',
            options={'verbose_name': 'Diagram Labeling Question'},
        ),
        migrations.RemoveField(
            model_name='diagramlabelingquestion',
            name='alternative_answers',
        ),
        migrations.RemoveField(
            model_name='diagramlabelingquestion',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='diagramlabelingquestion',
            name='label_position',
        ),
        migrations.AddField(
            model_name='diagramlabelingquestion',
            name='instruction',
            field=models.CharField(blank=True, help_text='Masalan: Label the diagram below', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='diagramlabelingquestion',
            name='diagram_image',
            field=models.ImageField(help_text='Rasm (diagram/map/table)', upload_to='diagrams/'),
        ),
        migrations.CreateModel(
            name='ImageLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_number', models.IntegerField(help_text='Rasm ichidagi raqam (1, 2, 3...)')),
                ('correct_answer', models.CharField(help_text="To'g'ri javob", max_length=255)),
                ('alternative_answers', models.TextField(blank=True, help_text='Har bir qatorda bitta (ixtiyoriy)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='exams.diagramlabelingquestion')),
            ],
            options={
                'ordering': ['label_number'],
                'unique_together': {('question', 'label_number')},
            },
        ),
    ]
